kind: pipeline
type: docker
name: default

services:
  - name: postgres
    image: postgres:12.0
    environment:
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
      POSTGRES_DB: odoo

steps:
  - name: test with OCB
    image: ghcr.io/oca/oca-ci/py3.10-ocb16.0:latest
    commands:
      - oca_install_addons
      - oca_init_test_database
      - oca_run_tests
  - name: test with Odoo
    image: ghcr.io/oca/oca-ci/py3.10-odoo16.0:latest
    commands:
      - oca_install_addons
      - oca_init_test_database
      - oca_run_tests
